<div id="footerDiv">
<table border="0" cellspacing="0" cellpadding="0" width="98%" style="margin-top:3px;" align="center">
  <tr><td align="center"><img src="images/1pgrey.gif" width="100%" height="1"></td></tr>
  <tr><td align="center"><span style="padding-left:0px;font-size:9px;color:#737579;"><!-- Copyright &copy; MA Software Systems 2011 --></span></td></tr>
  <tr><td height="2"></td></tr>
</table>
</div>