<%
if(viewDivision = "ABU") then
  adminDivision = "EHD-SAG"
end if
if(viewDivision = "GOMBU") then
  adminDivision = "EHD-SAG"
end if
if(viewDivision = "LABU") then
  adminDivision = "EHD-SAG"
end if
if(viewDivision = "WHCOBU") then
  adminDivision = "EHD-SAG"
end if

if(viewDivision = "BA:C") then
  adminDivision = "EH:DIV"
end if
if(viewDivision = "BA:L") then
  adminDivision = "EH:DIV"
end if
if(viewDivision = "BA:F") then
  adminDivision = "EH:DIV"
end if

if(viewDivision = "EBU") then
  adminDivision = "EHD-SAG"
end if
if(viewDivision = "EHCOBU") then
  adminDivision = "EHD-SAG"
end if
if(viewDivision = "IBU") then
  adminDivision = "EHD-SAG"
end if
if(viewDivision = "WABU") then
  adminDivision = "EHD-SAG"
end if
if(viewDivision = "SEABU") then
  adminDivision = "EHD-SAG"
end if
%>