<link rel="stylesheet" type="text/css" href="styles/ddlevelsmenu-base.css"/>
<link rel="stylesheet" type="text/css" href="styles/ddlevelsfiles/ddlevelsmenu-topbar.css" />
<link rel="stylesheet" type="text/css" href="styles/ddlevelsfiles/ddlevelsmenu-sidebar.css" />
<script type="text/javascript" src="script/ddlevelsmenu.js"></script>

<style>
li {
text-align: left;
}
</style>

<span id="ddtopmenubar" class="" style="border-bottom: 0px solid #000000;text-align: center;font-size: 14px;font-weight: bold;color: black;width: 100%;">
<a href="#" style="cursor:hand;text-decoration:none;color:black;" rel="ddsubmenu1">SMS Menu</a>
</span>

<script type="text/javascript">
ddlevelsmenu.setup("ddtopmenubar", "topbar") //ddlevelsmenu.setup("mainmenuid", "topbar|sidebar")
</script>

<ul id="ddsubmenu1" class="ddsubmenustyle">
<li><a href="#">iSRT</a>
  <ul>
  <li><a href="#">Stage</a>
    <ul>
    <li><a href="admin_StageInput.asp">Add Item</a></li>
    <li><a href="admin_StageList.asp">Listing</a></li>
    </ul>
  </li>
  <li><a href="#">Action Log</a>
    <ul>
    <li><a href="admin_LogInput.asp">Add Item</a></li>
    <li><a href="admin_LogDisplay.asp">Listing</a></li>
    </ul>
  </li>
  </ul>
</li>
<li><a href="#">ACS</a>
  <ul>
  <li><a href="#">Stage</a>
    <ul>
    <li><a href="divisional_StageInput.asp?viewdivision=ACS">Add Item</a></li>
    <li><a href="divisional_StageList.asp?viewdivision=ACS">Listing</a></li>
    </ul>
  </li>
  <li><a href="#">Action Log</a>
    <ul>
    <li><a href="divisional_LogInput.asp?viewdivision=ACS">Add Item</a></li>
    <li><a href="divisional_LogDisplay.asp?viewdivision=ACS">Listing</a></li>
    </ul>
  </li>
  </ul>
</li>
<li><a href="#">CGO</a>
  <ul>
  <li><a href="#">Stage</a>
    <ul>
    <li><a href="divisional_StageInput.asp?viewdivision=CGO">Add Item</a></li>
    <li><a href="divisional_StageList.asp?viewdivision=CGO">Listing</a></li>
    </ul>
  </li>
  <li><a href="#">Action Log</a>
    <ul>
    <li><a href="divisional_LogInput.asp?viewdivision=CGO">Add Item</a></li>
    <li><a href="divisional_LogDisplay.asp?viewdivision=CGO">Listing</a></li>
    </ul>
  </li>
  </ul>
</li>
<li><a href="#">FOP</a>
  <ul>
  <li><a href="#">Stage</a>
    <ul>
    <li><a href="divisional_StageInput.asp?viewdivision=FOP">Add Item</a></li>
    <li><a href="divisional_StageList.asp?viewdivision=FOP">Listing</a></li>
    </ul>
  </li>
  <li><a href="#">Action Log</a>
    <ul>
    <li><a href="divisional_LogInput.asp?viewdivision=FOP">Add Item</a></li>
    <li><a href="divisional_LogDisplay.asp?viewdivision=FOP">Listing</a></li>
    </ul>
  </li>
  </ul>
</li>
<li><a href="#">IFS</a>
  <ul>
  <li><a href="#">Stage</a>
    <ul>
    <li><a href="divisional_StageInput.asp?viewdivision=IFS">Add Item</a></li>
    <li><a href="divisional_StageList.asp?viewdivision=IFS">Listing</a></li>
    </ul>
  </li>
  <li><a href="#">Action Log</a>
    <ul>
    <li><a href="divisional_LogInput.asp?viewdivision=IFS">Add Item</a></li>
    <li><a href="divisional_LogDisplay.asp?viewdivision=IFS">Listing</a></li>
    </ul>
  </li>
  </ul>
</li>
<li><a href="#">OCC</a>
  <ul>
  <li><a href="#">Stage</a>
    <ul>
    <li><a href="divisional_StageInput.asp?viewdivision=OCC">Add Item</a></li>
    <li><a href="divisional_StageList.asp?viewdivision=OCC">Listing</a></li>
    </ul>
  </li>
  <li><a href="#">Action Log</a>
    <ul>
    <li><a href="divisional_LogInput.asp?viewdivision=OCC">Add Item</a></li>
    <li><a href="divisional_LogDisplay.asp?viewdivision=OCC">Listing</a></li>
    </ul>
  </li>
  </ul>
</li>
<li><a href="#">TOP</a>
  <ul>
  <li><a href="#">Stage</a>
    <ul>
    <li><a href="divisional_StageInput.asp?viewdivision=TOP">Add Item</a></li>
    <li><a href="divisional_StageList.asp?viewdivision=TOP">Listing</a></li>
    </ul>
  </li>
  <li><a href="#">Action Log</a>
    <ul>
    <li><a href="divisional_LogInput.asp?viewdivision=TOP">Add Item</a></li>
    <li><a href="divisional_LogDisplay.asp?viewdivision=TOP">Listing</a></li>
    </ul>
  </li>
  </ul>
</li>
<li><a href="#">Admin</a>
  <ul>
  <li><a href="loginRequests.asp">Login Requests</a>
  </li>
  <li><a href="updateProfile.asp">Update Profile</a>
  </li>
  </ul>
</li>
<li><a href="splash.asp">Home Page</a></li>
</ul>